main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('trt/', views.trt, name='trt'),
    path('trt/files_list', views.files_list_view, name='files_list'),
    path('trt/upload_file', views.upload_file, name='upload_file'),
    path('trt/delete_file<int:pk_file>', views.delete_file, name='delete_file'),
    path('trt/solver', views.solver_view, name='solver'),
    path('trt/parameters', views.parameters_view, name='parameters'),
    path('trt/parameters_edit<int:pk_param>',
         views.parameters_edit_view, name='parameters_edit'),
    path('trt/parameters_list', views.parameters_list_view, name='parameters_list'),
    path('trt/parameters_show<int:pk>',
         views.parameters_show_view, name='parameters_show'),
    path('trt/delete_parameters_model<int:pk_param>',
         views.delete_parameters_model, name='delete_parameters_model'),
    path('isp/', views.isp_view, name='isp'),
]

trtapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
import datetime

# Create your models here.


class UploadedFile(models.Model):
    file_name = models.CharField(max_length=100)
    file_object = models.FileField(upload_to='files')
    upload_date = models.DateTimeField(auto_now_add=True)
    file_desc = models.TextField(max_length=2000, default='')
    file_tag = models.CharField(max_length=20, default='ZSZI')

    def __str__(self):
        return self.file_name

    def delete(self, *args, **kwargs):
        self.file_object.delete()
        super().delete(*args, **kwargs)


class ParametersModel(models.Model):
    # Standard parameters
    model_name = models.CharField(max_length=250)
    model_desc = models.TextField(max_length=2000, default='')
    chosen_file = models.CharField(max_length=100)
    # Test parameters
    qv = models.FloatField(blank=True, null=True)
    q = models.FloatField(blank=True, null=True)
    v = models.FloatField(blank=True, null=True)
    # Medium properties
    cp_m = models.FloatField()
    ro_m = models.FloatField()
    mi_m = models.FloatField(blank=True, null=True)
    lam_m = models.FloatField(blank=True, null=True)
    # Rock properties
    cp = models.FloatField()
    ro = models.FloatField()
    alfa = models.FloatField(blank=True, null=True)
    T_g = models.FloatField(blank=True, null=True)
    # BHE properties
    H = models.FloatField()
    D_b = models.FloatField()
    d_out = models.FloatField(blank=True, null=True)
    d_inn = models.FloatField(blank=True, null=True)
    r_g = models.FloatField(blank=True, null=True)

    created_date = models.DateTimeField(
        auto_now_add=True)

    def __str__(self):
        return self.model_name

main/forms.py
from django import forms

from .models import UploadedFile, ParametersModel


class UploadedFileForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ('file_name', 'file_object', 'file_desc', 'file_tag')


class ParametersModelForm(forms.ModelForm):
    class Meta:
        model = ParametersModel
        fields = ('model_name', 'model_desc', 'chosen_file',
                 'qv', 'q', 'v', 'cp_m', 'ro_m', 'mi_m', 'lam_m',
                 'cp', 'ro', 'alfa', 'T_g', 'H', 'D_b', 'd_out', 'd_inn', 'r_g')

main/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse
from .models import UploadedFile, ParametersModel
from .forms import UploadedFileForm, ParametersModelForm
from plotly.offline import plot
# from plotly.subplots import make_subplots
import plotly.graph_objs as go
import pandas as pd
import os
from django.conf import settings
from .ispFuncs import IspFile
from .trtFuncs import Trt
# Create your views here.



def homepage(request):
    return render(request, 'main/home.html')


def isp_view(request):
    uploaded_files = UploadedFile.objects.filter(
        file_tag='ISP').order_by('-upload_date')
    if request.method == 'POST':
        chosen_file = request.POST.get('chosen_file')
        f = UploadedFile.objects.get(file_name=chosen_file)
    else:
        f = uploaded_files[0]

    isp = IspFile(f)
    plot_div = isp.plotIsp()
    stats = isp.get_all_stats()
    data = zip(plot_div, stats)
    return render(request, 'main/isp.html',
                  context={'files': uploaded_files,
                           'file_chosen': f,
                           'plot_shown': True,
                           'data': data,
                           })


def trt(request):
    return render(request, 'main/trt.html')


def files_list_view(request):
    uploaded_files = UploadedFile.objects.all().order_by('-upload_date')
    return render(request, 'main/files_list.html', {
        'files': uploaded_files,
    })


def solver_view(request):
    parameters_models = ParametersModel.objects.all().order_by('-created_date')
    if request.method == 'POST':
        chosen_model = request.POST.get('chosen_model')
        opts = request.POST.dict()
        p_model = ParametersModel.objects.get(model_name=chosen_model)
        print(p_model, opts)
        trt = Trt(p_model, opts)
        plot_div = trt.handle_all()
        params = None
        if 'fit_lin' in opts:
            if opts['fit_lin'] == '1':
                params = trt.yield_params()
        
        return render(request, 'main/solver.html',
                  context={'plot_div': plot_div,
                  'models': parameters_models,
                  'opts': opts,
                  'plot_shown': True,
                  'params': params,
                  })
    else:
        plot_div = None
    return render(request, 'main/solver_start.html',
                  context={'plot_div': plot_div,
                  'models': parameters_models})


def parameters_list_view(request):
    parameters_models = ParametersModel.objects.all().order_by('-created_date')
    return render(request, 'main/parameters_list.html', {
        'models': parameters_models, })


def parameters_show_view(request, pk=1):
    parameter_model = ParametersModel.objects.get(pk=pk)

    return render(request, 'main/parameters_show.html', {
        'model': parameter_model,
    })


def parameters_view(request):
    if request.method == 'POST':
        form = ParametersModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:parameters_list')
        else:
            print(form.errors)

    else:
        form = ParametersModelForm()
    uploaded_files = UploadedFile.objects.all().order_by('-upload_date')

    return render(request, 'main/parameters.html',
                  context={'files': uploaded_files,
                           'form': form, })


def parameters_edit_view(request, pk_param=None):
    # contet_instance = RequestConext(request)

    if request.method == 'POST':
        instance = None
        try:
            pk_param = request.POST['pk_param']
            instance = ParametersModel.objects.get(pk=pk_param)
        except:
            pass

        if instance is None:
            return redirect('main:parameters')
        else:
            form = ParametersModelForm(request.POST, instance=instance)
            if form.is_valid():
                form.save()
                return redirect('main:parameters_list')
            else:
                print(form.errors)
    else:
        try:
            instance = ParametersModel.objects.get(pk=pk_param)
            print(instance)
        except:
            pass
        form = ParametersModelForm(instance=instance)

    uploaded_files = UploadedFile.objects.all().order_by('-upload_date')

    return render(request, 'main/parameters_edit.html',
                  context={'files': uploaded_files,
                           'form': form,
                           'pk_param': pk_param, })


def upload_file(request):
    if request.method == 'POST':
        form = UploadedFileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('main:files_list')
    else:
        form = UploadedFileForm()
    return render(request, 'main/upload_file.html', {
        'form': form,
    })


def delete_file(request, pk_file):
    if request.method == 'POST':
        file_to_delete = UploadedFile.objects.get(pk=pk_file)
        file_to_delete.delete()
    return redirect('main:files_list')


def delete_parameters_model(request, pk_param):
    if request.method == 'POST':
        model_to_delete = ParametersModel.objects.get(pk=pk_param)
        model_to_delete.delete()
    return redirect('main:parameters_list')

main/templates/main/files_list.html
{% extends "main/files_wrapper.html" %}


{% block files %}
<h3 class="text-center">Dostępne pliki w bazie danych</h3>
<table class="table table-hover">
    <thead>
        <tr class="table">
            <th>Nazwa</th>
            <th>Data</th>
            <th>Pobierz</th>
            <th>Usuń</th>
        </tr>
    </thead>
    <tbody>
        {% for file in files %}
        <tr class="table">
            <td>{{ file.file_name }}</td>
            <td> {{ file.upload_date }}</td>
            <td>
                <a href="{{ file.file_object.url }}" class="btn btn-primary bt-sm" data-toggle="tooltip" data-placement="top" title="Pobierz plik" target="_blank">Pobierz</a>
            </td>
            <td>
                <form action="{% url 'main:delete_file' file.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger bt-sm" data-toggle="tooltip" data-placement="top" title="Usuń plik z serwera">Usuń</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

main/templates/main/parameters.html
{% extends "main/parameters_wrapper.html" %}

{% block parameters %}
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="form-group">
    <label class="col-form-label" for="id_model_name">Nazwa modelu</label>
    <input type="text" class="form-control" name='model_name' maxlength="250" placeholder="Nazwa modelu"
      id="id_model_name">
  </div>

  <div class="form-group">
    <label class="col-form-label" for="id_model_desc">Opis modelu</label>
    <input type="text" class="form-control" name='model_desc' maxlength="2000" placeholder="Opis modelu"
      id="id_model_desc">
  </div>

  <div class="form-group">
    <label for="id_chosen_file">Wybierz plik</label>
    <select class="form-control" id="id_chosen_file" name='chosen_file'>
      {% for file in files %}
      <option> {{ file.file_name }} </option>
      {% endfor %}
    </select>
  </div>

  <label for="test_param">
    <h5>Paramtery testu</h3>
  </label>
  <div class="row" id="test_param">
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_qv">Średni przepływ [m^3/s]</label>
        <input type="text" class="form-control" name='qv' placeholder="qv" id="id_qv">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_q">Średnia moc cieplna [W]</label>
        <input type="text" class="form-control" name='q' placeholder="q" id="id_q">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_v">Średnia prędkość przepływu [m/s]</label>
        <input type="text" class="form-control" name='v' placeholder="v" id="id_v">
      </div>
    </div>
  </div>

  <label for="medium">
    <h5>Parametry medium</h5>
  </label>
  <div class="row" id="medium">

    <br>
    <div class="col">
      <div class="form-group" style=>
        <label class="col-form-label" for="id_cp_m">Ciepło właściwe [J/(kgK)]</label>
        <input type="text" class="form-control" name="cp_m" placeholder="cp_m" id="id_cp_m">
      </div>
      <div class="form-group">
        <label class="col-form-label" for="ro_m">Gęstość medium [kg/m^3]</label>
        <input type="text" class="form-control" name="ro_m" placeholder="ro_m" id="id_ro_m">
      </div>
    </div>

    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_mi_m">Współczynnik lepkości dynaminczej [x]</label>
        <input type="text" class="form-control" name="mi_m" placeholder="mi_m" id="id_mi_m">
      </div>
      <div class="form-group">
        <label class="col-form-label" for="id_lam_m">Współczynnik przewodzenia ciepła [x]</label>
        <input type="text" class="form-control" name="lam_m" placeholder="lam_m" id="id_lam_m">
      </div>
    </div>
  </div>

  <label for="rocks">
    <h5>Parametry górotworu</h5>
  </label>
  <div class="row" id="rocks">
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_cp">Ciepło właściwe [J/(kgK)]</label>
        <input type="text" class="form-control" name='cp' placeholder="cp" id="id_cp">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_ro">Gęstość [kg/m^3]</label>
        <input type="text" class="form-control" name='ro' placeholder="ro" id="id_ro">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_alfa">Dyfuzyjność [x]</label>
        <input type="text" class="form-control" name='alfa' placeholder="&#945" id="id_alfa">
      </div>
    </div>
  </div>

  <label for="bhex">
    <h5>Parametry wymiennika</h5>
  </label>
  <div class="row" id="bhex">
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_H">Głębkość wymiennika [m]</label>
        <input type="text" class="form-control" name='H' placeholder="h" id="id_H">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_D_b">Średnica otworu [m]</label>
        <input type="text" class="form-control" name='D_b' placeholder="db" id="id_D_b">
      </div>
    </div>
  </div>

  <div class="row" id="bhex_2">
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_d_out">Średnica zewnętrzna rury [m]</label>
        <input type="text" class="form-control" name='d_out' placeholder="d_out" id="id_d_out">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_d_inn">Średnica wewnętrzna rury [m]</label>
        <input type="text" class="form-control" name='d_inn' placeholder="d_inn" id="id_d_inn">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_r_g">Grubość ścianki rury [m]</label>
        <input type="text" class="form-control" name='r_g' placeholder="r_g" id="id_r_g">
      </div>
    </div>
  </div>


  <button type="submit" class="btn btn-primary" data-toggle="tooltip" data-placement="top"
    title="Zapisz parametry">Zapisz</button>
  {{ form.errors }}
  {{ form.non_field_errors }}
</form>

{% endblock %}

main/templates/main/parameters_edit.html
{% extends "main/parameters_wrapper.html" %}

{% block parameters %}
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="form-group">
    <label class="col-form-label" for="id_model_name">Nazwa modelu</label>
    <input type="text" class="form-control" name='model_name' maxlength="250" placeholder="Nazwa modelu"
      id="id_model_name" value="{{form.model_name.value}}">
  </div>

  <div class="form-group">
    <label class="col-form-label" for="id_model_desc">Opis modelu</label>
    <input type="text" class="form-control" name='model_desc' maxlength="2000" placeholder="Opis modelu"
      id="id_model_desc" value="{{form.model_desc.value}}">
  </div>

  <div class="form-group">
    <label for="id_chosen_file">Wybierz plik</label>
    <select class="form-control" id="id_chosen_file" name='chosen_file'>
      {% for file in files %}
      {% if form.chosen_file.value == file.file_name %}
      <option selected="selected"> {{ file.file_name }} </option>
      {% else %}
      <option> {{ file.file_name }} </option>
      {% endif %}
      {% endfor %}
    </select>
  </div>

  <label for="test_param">
    <h5>Paramtery testu</h3>
  </label>
  <div class="row" id="test_param">
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_qv">Średni przepływ [m<sup>3</sup>/s]</label>
        <input type="text" class="form-control" name='qv' value="{{form.qv.value}}" id="id_qv">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_q">Średnia moc cieplna [W]</label>
        <input type="text" class="form-control" name='q' value="{{form.q.value}}" id="id_q">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_v">Średnia prędkość przepływu [m/s]</label>
        <input type="text" class="form-control" name='v' value="{{form.v.value}}" id="id_v">
      </div>
    </div>
  </div>

  <label for="medium">
    <h5>Parametry medium</h5>
  </label>
  <div class="row" id="medium">

    <br>
    <div class="col">
      <div class="form-group" style=>
        <label class="col-form-label" for="id_cp_m">Ciepło właściwe [J/(kg&#183;K)]</label>
        <input type="text" class="form-control" name="cp_m" value="{{form.cp_m.value}}" id="id_cp_m">
      </div>
      <div class="form-group">
        <label class="col-form-label" for="ro_m">Gęstość medium [kg/m<sup>3</sup>]</label>
        <input type="text" class="form-control" name="ro_m" value="{{form.ro_m.value}}" id="id_ro_m">
      </div>
    </div>

    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_mi_m">Współczynnik lepkości dynaminczej [Pa&#183;s]</label>
        <input type="text" class="form-control" name="mi_m" value="{{form.mi_m.value}}" id="id_mi_m">
      </div>
      <div class="form-group">
        <label class="col-form-label" for="id_lam_m">Współczynnik przewodzenia ciepła [W/(m&#183;K)]</label>
        <input type="text" class="form-control" name="lam_m" value="{{form.lam_m.value}}" id="id_lam_m">
      </div>
    </div>
  </div>

  <label for="rocks">
    <h5>Parametry górotworu</h5>
  </label>
  <div class="row" id="rocks">
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_cp">Ciepło właściwe [J/(kg&#183;K)]</label>
        <input type="text" class="form-control" name='cp' value="{{form.cp.value}}" id="id_cp">
      </div>
      <!-- </div>
    <div class="col"> -->
      <div class="form-group">
        <label class="col-form-label" for="id_ro">Gęstość [kg/m<sup>3</sup>]</label>
        <input type="text" class="form-control" name='ro' value="{{form.ro.value}}" id="id_ro">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_alfa">Dyfuzyjność [m<sup>2</sup>/s]</label>
        <input type="text" class="form-control" name='alfa' value="{{form.alfa.value}}" id="id_alfa">
      </div>
      <div class="form-group">
        <label class="col-form-label" for="id_T_g">Temperatura niezakłócona [&#176;C]</label>
        <input type="text" class="form-control" name='T_g' value="{{form.T_g.value}}" id="id_T_g">
      </div>
    </div>
  </div>

  <label for="bhex">
    <h5>Parametry wymiennika</h5>
  </label>
  <div class="row" id="bhex">
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_H">Głębkość wymiennika [m]</label>
        <input type="text" class="form-control" name='H' value="{{form.H.value}}" id="id_H">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_D_b">Średnica otworu [m]</label>
        <input type="text" class="form-control" name='D_b' value="{{form.D_b.value}}" id="id_D_b">
      </div>
    </div>
  </div>

  <div class="row" id="bhex_2">
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_d_out">Średnica zewnętrzna rury [m]</label>
        <input type="text" class="form-control" name='d_out' value="{{form.d_out.value}}" id="id_d_out">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_d_inn">Średnica wewnętrzna rury [m]</label>
        <input type="text" class="form-control" name='d_inn' value="{{form.d_inn.value}}" id="id_d_inn">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label" for="id_r_g">Grubość ścianki rury [m]</label>
        <input type="text" class="form-control" name='r_g' value="{{form.r_g.value}}" id="id_r_g">
      </div>
    </div>
  </div>


  <button type="submit" class="btn btn-primary" data-toggle="tooltip" data-placement="top"
    title="Zapisz parametry">Zapisz</button>
  <input name="pk_param" value="{{pk_param}}" style="display: none;"></input>
  {{ form.errors }}
  {{ form.non_field_errors }}
</form>

{% endblock %}

main/templates/main/parameters_list.html
{% extends "main/parameters_wrapper.html" %}

{% block parameters %}

<h3 class="text-center">Dostępne modele parametrów w bazie danych</h3>
<table class="table table-hover">
  <thead>
    <tr class="table">
      <th>Nazwa</th>
      <th>Data</th>
      <th>Edytuj</th>
      <th>Pokaż</th>
      <th>Usuń</th>
    </tr>
  </thead>
  <tbody>
    {% for model in models %}
    <tr class="table">
      <td>{{ model.model_name }}</td>
      <td> {{ model.created_date }}</td>
      <td>
        <a href="{% url 'main:parameters_edit' model.pk %}">
          <!-- {% csrf_token %} -->
          <!-- <input name="pk_param" value="{{model.pk}}" style="display: none;"></input> -->
          <button class="btn btn-primary bt-sm" data-toggle="tooltip" data-placement="top"
            title="Edytuj wartości modelu">Edytuj</a>
        </a>
      </td>
      <td>
        <form action="{% url 'main:parameters_show' model.pk %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary bt-sm" data-toggle="tooltip" data-placement="top"
            title="Pokaż wartości">Pokaż</a>
        </form>
      </td>
      <td>
        <form action="{% url 'main:delete_parameters_model' model.pk %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger bt-sm" data-toggle="tooltip" data-placement="top"
            title="Usuń model z serwera">Usuń</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

main/templates/main/parameters_show.html
{% extends "main/parameters_wrapper.html" %}

{% block parameters %}
<div class="text-center">
  <div class="form-group">
    <label class="col-form-label text-info" for="id_model_name"><h3>Model</h3></label>
    <div class="container border border-info rounded-pill" id="id_model_name">
      <h4>{{ model.model_name }}</h4>
    </div>
  </div>

  <div class="form-group">
    <label class="col-form-label text-info" for="id_model_desc"><h3>Opis</h3></label>
    <div class="container border border-info rounded-pill" id="id_model_desc">
      <h4>{{ model.model_desc }}</h4>
    </div>
  </div>

  <div class="form-group">
    <label class="col-form-label text-info" for="id_chosen_file"><h3>Plik</h3></label>
    <div class="container border border-info rounded-pill" id="id_chosen_file">
      <h4>{{ model.chosen_file }}</h4>
    </div>
  </div>

  <br>

  <label class="text-info" for="test_param">
    <h3>Paramtery testu</h3>
  </label>

  <div class="row border border-info rounded-pill" id="test_param">
    <div class="col">
      <div class="form-group">
        <label class="col-form-label text-muted" for="id_qv">Średni przepływ [m<sup>3</sup>/s]</label>
        <div class="container" id="id_qv">
          <h4>{{ model.qv }}</h4>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label text-muted" for="id_q">Średnia moc cieplna [W]</label>
        <div class="container" id="id_q">
          <h4>{{ model.q }}</h4>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label text-muted" for="id_v">Średnia prędkość przepływu [m/s]</label>
        <div class="container" id="id_v">
          <h4>{{ model.v }}</h4>
        </div>
      </div>
    </div>
  </div>

  <br>

  <label class="text-info" for="medium">
    <h3>Parametry medium</h3>
  </label>
  <div class="row border border-info rounded-pill id=" medium">

    <div class="col">
      <div class="form-group" style=>
        <label class="col-form-label text-muted" for="id_cp_m">Ciepło właściwe [J/(kg&#183;K)]<</label>
        <div class="container" id="id_cp_m">
          <h4>{{ model.cp_m }}</h4>
        </div>
      </div>
      <div class="form-group">
        <label class="col-form-label text-muted" for="ro_m">Gęstość medium [kg/m<sup>3</sup>]</label>
        <div class="container" id="id_ro_m">
          <h4>{{ model.ro_m }}</h4>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="form-group">
        <label class="col-form-label text-muted" for="id_mi_m">Współczynnik lepkości dynaminczej [Pa&#183;s]</label>
        <div class="container" id="id_mi_m">
          <h4>{{ model.mi_m }}</h4>
        </div>
      </div>
      <div class="form-group">
        <label class="col-form-label text-muted" for="id_lam_m">Współczynnik przewodzenia ciepła [W/(m&#183;K)]</label>
        <div class="container" id="id_lam_m">
          <h4>{{ model.lam_m }}</h4>
        </div>
      </div>
    </div>
  </div>

  <br>

  <label class="text-info" for="rocks">
    <h3>Parametry górotworu</h3>
  </label>
  <div class="row border border-info rounded-pill" id="rocks">
    <div class="col">
      <div class="form-group">
        <label class="col-form-label text-muted" for="id_cp">Ciepło właściwe [J/(kg&#183;K)]</label>
        <div class="container" id="id_cp">
          <h4>{{ model.cp }}</h4>
        </div>
      </div>
    <!-- </div>
    <div class="col"> -->
      <div class="form-group">
        <label class="col-form-label text-muted" for="id_ro">Gęstość [kg/m<sup>3</sup>]</label>
        <div class="container" id="id_ro">
          <h4>{{ model.ro }}</h4>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label class="col-form-label text-muted" for="id_alfa">Dyfuzyjność [m<sup>2</sup>/s]</label>
        <div class="container" id="id_alfa">
          <h4>{{ model.alfa }}</h4>
        </div>
      </div>
      <div class="form-group">
        <label class="col-form-label text-muted" for="id_T_g">Temperatura niezakłócona [&#176;C]</label>
        <div class="container" id="id_T_g">
          <h4>{{ model.T_g }}</h4>
        </div>
      </div>
    </div>
  </div>

  <br>

  <label class="text-info" for="bhex">
    <h3>Parametry wymiennika</h3>
  </label>
  <div class="border border-info rounded-pill">
    <div class="row" id="bhex">
      <div class="col">
        <div class="form-group">
          <label class="col-form-label text-muted" for="id_h">Głębkość wymiennika [m]</label>
          <div class="container" id="id_h">
            <h4>{{ model.H }}</h4>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label class="col-form-label text-muted" for="id_db">Średnica otworu [m]</label>
          <div class="container" id="id_db">
            <h4>{{ model.D_b }}</h4>
          </div>
        </div>
      </div>
    </div>

    <div class="row" id="bhex_2">
      <div class="col">
        <div class="form-group">
          <label class="col-form-label text-muted" for="id_d_out">Średnica zewnętrzna rury [m]</label>
          <div class="container" id="id_d_out">
            <h4>{{ model.d_out }}</h4>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label class="col-form-label text-muted" for="id_d_inn">Średnica wewnętrzna rury [m]</label>
          <div class="container" id="id_d_inn">
            <h4>{{ model.d_inn }}</h4>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label class="col-form-label text-muted" for="id_r_g">Grubość ścianki rury [m]</label>
          <div class="container" id="id_r_g">
            <h4>{{ model.r_g }}</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/trt.html
{% extends "main/base_layout.html" %}

{% block content %}
<div class="jumbotron">
    
        <h2>TRT</h2>
    
</div>
{% endblock %}